apiVersion: v2
name: misp
description: A MISP Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/xNaaro/misp-helm.git
maintainers:
  - email: dabarren@gmail.com
    name: xNaaro/Eduardo Gonzalez
dependencies:
  - condition: redis.enabled
    name: redis
    version: 20.6.2
    repository: https://charts.bitnami.com/bitnami
  - condition: mysql.enabled
    name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 12.2.1
  - condition: mariadb.enabled
    name: mariadb
    version: 20.2.1
    repository: https://charts.bitnami.com/bitnami