apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misp-helm.fullname" . }}
  labels:
    {{- include "misp-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "misp-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "misp-helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "misp-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.misp.image.repository }}:{{ .Values.misp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.misp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.misp.target_port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe.misp | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.misp | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: ECS_LOG_ENABLED
              value: "yes"
            - name: MISP_BASEURL
              value: {{ .Values.base_url }}
            - name: MISP_DEBUG
              value: "yes"
            - name: MISP_EMAIL
              value: ahoj@example.com
            - name: MISP_MODULE_URL
              value: http://{{ include "misp-helm.fullname" . }}-modules
            - name: MISP_ORG
              value: Testingorg
            - name: MISP_UUID
              value: 0a674a5a-c4cb-491d-80cf-5adb48b5c1cd
            - name: MYSQL_DATABASE
              value: misp
            - name: MYSQL_HOST
              value: {{ include "misp-helm.fullname" . }}-mariadb
            - name: MYSQL_LOGIN
              value: {{ .Values.mysql.auth.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.auth.password }}
            - name: REDIS_HOST
              value: {{ include "misp-helm.fullname" . }}-redis-master
            - name: SECURITY_SALT
              value: PleaseChangeForProduction
            - name: SYSLOG_ENABLED
              value: "no"
            - name: ZEROMQ_ENABLED
              value: "yes"
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}