apiVersion: v1
kind: Service
metadata:
  name: {{ include "misp-helm.fullname" . }}
  labels:
    {{- include "misp-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.misp.type }}
  ports:
    - port: {{ .Values.services.misp.port }}
      targetPort: {{ .Values.services.misp.target_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "misp-helm.selectorLabels" . | nindent 4 }}